# Generated by Django 2.2.2 on 2019-09-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usercoupon',
        ),
    ]
