# Generated by Django 2.2.2 on 2019-09-26 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0002_delete_usercoupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usercoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('type', models.IntegerField(default=0, verbose_name='优惠券类型')),
                ('code', models.IntegerField(default='', verbose_name='优惠券唯一编码')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='优惠券开始时间')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='优惠券结束时间')),
                ('money', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='优惠券金额')),
                ('condition', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='满多少钱可以使用')),
                ('is_use', models.IntegerField(verbose_name='是否使用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usercoupon',
            },
        ),
    ]
