# Generated by Django 2.1.5 on 2019-10-14 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0012_auto_20191014_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='code',
            field=models.CharField(default='', max_length=255, verbose_name='优惠券唯一编码'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 15, 57, 43, 420062, tzinfo=utc), verbose_name='会员结束时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 15, 57, 43, 420062, tzinfo=utc), verbose_name='会员开始时间'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 15, 57, 43, 421063, tzinfo=utc), verbose_name='优惠券结束时间'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 15, 57, 43, 421063, tzinfo=utc), verbose_name='优惠券开始时间'),
        ),
    ]
