# Generated by Django 2.1.5 on 2019-10-16 06:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0015_auto_20191015_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderrecord',
            name='num',
            field=models.IntegerField(default=0, verbose_name='消耗积分'),
        ),
        migrations.AddField(
            model_name='rule',
            name='invite_award',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='rule',
            name='learn_award',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 40, 55, 527196, tzinfo=utc), verbose_name='会员结束时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 40, 55, 527196, tzinfo=utc), verbose_name='会员开始时间'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 40, 55, 513194, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 40, 55, 513194, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 40, 55, 528193, tzinfo=utc), verbose_name='优惠券结束时间'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 6, 40, 55, 528193, tzinfo=utc), verbose_name='优惠券开始时间'),
        ),
    ]
