# Generated by Django 2.1.5 on 2019-10-16 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0017_auto_20191016_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrecord',
            old_name='cid',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='orderrecord',
            old_name='uid',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 10, 52, 6, 448124, tzinfo=utc), verbose_name='会员结束时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 10, 52, 6, 448124, tzinfo=utc), verbose_name='会员开始时间'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 10, 52, 6, 419119, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 10, 52, 6, 419119, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 10, 52, 6, 449124, tzinfo=utc), verbose_name='优惠券结束时间'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 10, 52, 6, 449124, tzinfo=utc), verbose_name='优惠券开始时间'),
        ),
    ]
