# Generated by Django 2.1.5 on 2019-10-17 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0020_auto_20191017_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='date',
            field=models.DateField(verbose_name='活动时间定为到天'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 11, 41, 30, 365120, tzinfo=utc), verbose_name='会员结束时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 11, 41, 30, 364101, tzinfo=utc), verbose_name='会员开始时间'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 11, 41, 30, 330098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 11, 41, 30, 330098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='time',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='time',
            name='start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 11, 41, 30, 366107, tzinfo=utc), verbose_name='优惠券结束时间'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 11, 41, 30, 366107, tzinfo=utc), verbose_name='优惠券开始时间'),
        ),
    ]
