# Generated by Django 2.1.5 on 2019-10-17 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0022_auto_20191017_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='sk',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 15, 46, 1, 481308, tzinfo=utc), verbose_name='会员结束时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 15, 46, 1, 481308, tzinfo=utc), verbose_name='会员开始时间'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 15, 46, 1, 436306, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 15, 46, 1, 436306, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 15, 46, 1, 483309, tzinfo=utc), verbose_name='优惠券结束时间'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 15, 46, 1, 483309, tzinfo=utc), verbose_name='优惠券开始时间'),
        ),
    ]
