# Generated by Django 2.1.5 on 2019-10-22 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0024_auto_20191022_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 7, 27, 45, 970522, tzinfo=utc), verbose_name='会员结束时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 7, 27, 45, 970522, tzinfo=utc), verbose_name='会员开始时间'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 7, 27, 45, 943520, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 7, 27, 45, 943520, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='linknum',
            field=models.IntegerField(default=0, verbose_name='点赞树'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_browse',
            field=models.IntegerField(default=0, verbose_name='实验报告浏览量'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 7, 27, 45, 971521, tzinfo=utc), verbose_name='优惠券结束时间'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 7, 27, 45, 971521, tzinfo=utc), verbose_name='优惠券开始时间'),
        ),
    ]
